image: node:alpine

cache:
  paths:
  - node_modules/

test:
  stage: test
  services:
    - mongo
  tags:
   - node
  variables:
    MONGODB_URI: 'mongodb://mongo/runner'
    NODE_ENV: 'test'
  script:
   - npm install --silent
   - npm run test
