apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cnet-to-collection
spec:
  schedule: "15 07 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: stream2db
            image: poder/stream2db:0.2.4
            args:
            - cnet2Collection
            env:
            - name: "MONGODB_URI"
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: mongodburi
            - name: "NODE_ENV"
              value: "production"
          restartPolicy: OnFailure
